# Generated by Django 3.2 on 2023-02-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('date_joined',), 'verbose_name': 'пользователя', 'verbose_name_plural': 'пользователи'},
        ),
    ]
