# Generated by Django 3.2 on 2023-03-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-date_joined',), 'verbose_name': 'пользователя', 'verbose_name_plural': 'пользователи'},
        ),
    ]
