# Generated by Django 3.2 on 2023-02-25 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='НАЗВАНИЕ ПРОЕКТА')),
                ('href', models.URLField(verbose_name='ССЫЛКА НА РЕПОЗИТОРИЙ')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=512, verbose_name='ТЕКСТ ЗАМЕТКИ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='СОЗДАНО')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ОБНОВЛЕНО')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='ПРИЗНАК АКТИВНОСТИ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to=settings.AUTH_USER_MODEL, verbose_name='АВТОР')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='ПРОЕКТ')),
            ],
            options={
                'verbose_name': 'заметку',
                'verbose_name_plural': 'заметки',
            },
        ),
    ]
