# Generated by Django 3.2 on 2023-02-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-pk',), 'verbose_name': 'проект', 'verbose_name_plural': 'проекты'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-pk',), 'verbose_name': 'заметку', 'verbose_name_plural': 'заметки'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ПРИЗНАК ОТКРЫТОСТИ'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(blank=True, verbose_name='ТЕКСТ ЗАМЕТКИ'),
        ),
    ]
