POST http://127.0.0.1:8000/api/jwt-token/refresh/
Content-Type: application/json

{
    "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY0OTAwNzAwMywiaWF0IjoxNjQ4OTIwNjAzLCJqdGkiOiI2OTJhNzk4MmE5MTY0NjY0ODUxZmE1MGFjOWZjMGRlYSIsInVzZXJfaWQiOiIzYjJmMWJhMS1jYWUxLTQ0ZDYtODEzMS1hM2IxODhlZjZmMDIifQ.enGL4V9dIWDbTwWAI0ZSx8K7-9sGLE6jloLEVajVPgM"
}
